name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
change-template: '- $TITLE #$NUMBER [@$AUTHOR]'

categories:
  - title: "✨ Features"
    labels: 
      - "feature"
      - "enhancement"
      - "✨"
      - "⚡️"
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - '🐛'
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
      - "📚"
  - title: " 🚨 Testing"
    labels: 
      - "testing"
      - "test"
  - title: " 🔨 Maintance"
    labels: 
      - "Maintenance"
 
exclude-labels:
  - "changelog: skip"

template: |
  
  ## whylogs release v$NEXT_PATCH_VERSION

  Hi everyone! We’ve now released whylogs $NEXT_PATCH_VERSION 🚀.
  Whylogs is an open standard for data and ML logging created by WhyLabs. 👩🏽‍🔬

  This version includes: 
  
  $CHANGES
