version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
    pre_build:
      - which python
      - which pip
      - cd python && poetry config virtualenvs.create false --local && poetry install -E docs
      - cd python && poetry run which python
      - pip list

sphinx:
   configuration: python/docs/conf.py
