version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry 1.4.1
      - asdf global poetry 1.4.1
      - cd python && poetry export -E docs --without-hashes -f requirements.txt --output requirements.txt
      - cd python/docs && make pre-build
sphinx:
  configuration: python/docs/conf.py

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: python/requirements.txt
