version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - curl -sSL https://install.python-poetry.org | python -
      - which python
      - which pip
      - cd python && $HOME/.poetry/bin/poetry config virtualenvs.create false --local && $HOME/.poetry/bin/poetry install -E docs
      - cd python && $HOME/.poetry/bin/poetry run which python
      - pip list

sphinx:
   configuration: python/docs/conf.py
