version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - curl -sSL https://install.python-poetry.org | python -
      - cd python && /home/docs/.local/bin/poetry export -E docs --without-hashes -f requirements.txt --output requirements.txt && pip install requirements.txt

sphinx:
   configuration: python/docs/conf.py
