version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - cd python && poetry config virtualenvs.create false && poetry install -E docs

sphinx:
   configuration: python/docs/conf.py
