version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    pre_build:
      - which python
      - which pip
      - cd python && poetry config virtualenvs.create false --local && poetry install -E docs
      - cd python && poetry run which python
      - pip list

sphinx:
   configuration: python/docs/conf.py
