blank_issues_enabled: false
contact_links:
  - name: "Support or Questions"
    url: http://join.slack.whylabs.ai/
    about: Join us in our slack, we always happy to help, or just to hear how you are using whylogs.