
project: s3_example_project
pipeline: latest_results
verbose: false
writers:
- formats:
  - protobuf
  output_path: s3://super_awesome_bucket/
  path_template: $name/dataset_summary
  filename_template: dataset_summary
  type: s3
- formats:
  - flat
  output_path: s3://super_awesome_bucket/
  path_template: $name/dataset_summary
  filename_template: dataset_summary
  type: s3
- formats:
  - json
  output_path: s3://super_awesome_bucket/
  path_template: $name/dataset_summary
  filename_template: dataset_summary
  type: s3
