project: example-project
pipeline: example-pipeline
verbose: false
writers:
- data_collection_consent: true
  formats: ['protobuf']
  output_path: whylabs
  type: whylabs
- data_collection_consent: true
  formats: ['protobuf']
  output_path: mlflow
  type: mlflow