name: Nightly Docker test

on:
  schedule:
    - cron "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Test Dockerfile.dev
      run: |
        docker build -t whylogs -f Dockerfile.dev .
	docker run --rm -it -v $(pwd):/workspace whylogs docker_test.sh
