name: Nightly Docker test

on:
  pull_request:
  push:
    branches: [mainline, 1.0.x]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
#  schedule:
#    - cron "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test Dockerfile
        run: |
          docker build -t whylogs -f Dockerfile .
          docker run --rm -it -v $(pwd):/workspace whylogs ./docker_test.sh
