name: markdown-link-check

on: workflow_dispatch

defaults:
  run:
    working-directory: python
jobs:
    markdown-link-check:
    needs: docs-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"